FROM anapsix/alpine-java
MAINTAINER myNAME 
ADD target/alunos-persist-jar-with-dependencies.jar /home/alunos-persist-jar-with-dependencies.jar
CMD ["java","-jar","/home/alunos-persist-jar-with-dependencies.jar"]
